<?php
/**
 * GM Panel
 * 
 * Шаблон ошибки подключения к базе данных.
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Green
 * @since 1.0
 */
?>
<!DOCTYPE HTML>
<html lang="en-GB">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Error connecting to database</title>
    <link type="image/png" href="<?= Gm::getAlias('@theme::/assets/ico/favicon.ico') ?>" rel="icon" sizes="16x16">
    <link rel="stylesheet" href="<?= Gm::getAlias('@theme::/assets/css/error.css') ?>" />
</head>

<body class="gm-error gm-error_db">
    <div class="gm-error__wrapper">
        <div class="gm-error__title"><?= Gm::$app->version->nameToHtml() ?><span class="copyright">&copy;</span></div>
        <div class="gm-error__text">
            <div class="gm-error__icon gm-error__icon-db"><?= $exception->getDispatch() ?></div>
        </div>
    </div>
</body>

</html>