<?php
/**
 * GM Panel
 * 
 * Шаблон ошибки 403 (Forbidden).
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Green
 * @since 1.0
 */
?>
<!DOCTYPE HTML>
<html lang="ru-RU">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ошибка 403 (Запрещено)</title>
    <link type="image/png" href="<?= Gm::getAlias('@theme::/assets/ico/favicon.ico') ?>" rel="icon" sizes="16x16">
    <link rel="stylesheet" href="<?= Gm::getAlias('@theme::/assets/css/error.css') ?>" />
</head>

<body class="gm-error gm-error_403">
    <div class="gm-error__wrapper">
        <h1 class="gm-error__header">Ошибка 403 (Запрещено)</h1>
        <div class="gm-error__text">
            <p>Доступ к данной странице запрещен.</p>
            <ol>
                <li>Кликните дважды по URL адресу в адресной строке браузера, возможно, вы неверно ввели адрес страницы. </li>
                <li>Очистите кэш вашего браузера. Кэшированная версия страницы, на которую вы пытались зайти, может быть причиной возникновения ошибки. </li>
                <li>Попробуйте залогиниться снова. </li>
            </ol>
        </div>
    </div>
</body>

</html>